### ISSUE TITLE
Transaction, created by Snowball was rejected due missing UTXO

### ISSUE THREAD

**Issue by echupriyanov** [stegos/stegos#1077]

**Comment by echupriyanov** [comment]
Checkout saved search in Kibana: "Bad transaction"

**Comment by echupriyanov** [comment]
Also: https://foxtrot.aws.stegos.com/app/kibana#/discover/0bf8bff0-a222-11e9-8410-758d121a4915?_g=(refreshInterval:(pause:!f,value:5000),time:(from:now-30m,mode:quick,to:now))

**Comment by rtsisyk** [comment]
Should be fixed, please re-open if problem still exists.
