### ISSUE TITLE
Vulnerable `memoffset` crate

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#1149]
`cargo audit` reports:
```
ID:	 RUSTSEC-2019-0011
Crate:	 memoffset
Version: 0.2.1
Date:	 2019-07-16
URL:	 https://github.com/Gilnaa/memoffset/issues/9#issuecomment-505461490
Title:	 Flaw in offset_of and span_of causes SIGILL, drops uninitialized memory of arbitrary type on panic in client code
Solution: upgrade to: >= 0.5.0

error: 1 vulnerability found!

```

In original comment they have found a bug in memoffset that was build on aarch64.

Currently tokio 0.1.22 depend on crossbeam, which use this `memoffset` crate.

So for temporary measure we can disable cargo-audit from our CI. and use it localy, untill crossbeam would not upgrade their dependencies.

**Comment by rtsisyk** [comment]
Fixed
