### ISSUE TITLE
WebSocket API doesn't respond on PING during account recovery

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1240]

**Comment by rtsisyk** [comment]
WebSocket API is not even started during recovery. See #1132

**Comment by echupriyanov** [comment]
`recovery` here means `unseal` account, and getting balance after unsealing

**Comment by rtsisyk** [comment]
RocksDB blocks NodeService. We should use a snapshot for recovering wallet. 

https://github.com/stegos/stegos/issues/1079
