### ISSUE TITLE
Harden Snowball

### ISSUE THREAD

**Issue by dbmcclain** [stegos/stegos#1249]
Make fixed participation fee
Fee no longer needs to be cloaked
Every participant will provide 5 UTXOs

Hence, blame discovery phase cannot reveal who has supplied how many UTXO's. All participants supply 5 UTXO, even if some are zero-amount dummies. This leads to a combinatorial confusion factor of more than 2 Million possibilities among 10 participants.

**Comment by rtsisyk** [comment]
Nothing else to do.
