### ISSUE TITLE
CLI password reading didn't work on windows

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#1293]
Its impossible to create account, and to unseal account because of that.
Thats why CLI didn't work on Windows.

**Comment by rtsisyk** [comment]
Sounds strange. `rpassword` crate definitely has Windows support.

**Comment by vldm** [comment]
As author of rpassword said, he didn't use Windows, so this is not a point.

Additionally on wine, cli didn't work completely, so this problem can be related to some misscompiliation, or readline problems.

**Comment by vldm** [comment]
It's looks like it already fixed. At least on my pc - with new version of rpassword cli works fine.
