### ISSUE TITLE
flint/flint.h: No such file or directory

### ISSUE THREAD

**Issue by gitslagga** [stegos/stegos#1294]
here is a problem, when i run cargo build --release:
......
cargo:warning=src/dicemix/solver_flint.cpp:4:10: fatal error: flint/flint.h: No such file or directory

**Comment by gitslagga** [comment]
in this wallet build document:
https://github.com/stegos/stegos/blob/dev/BUILD.md

**Comment by rtsisyk** [comment]
Hi! Please install libflint library to `/usr/local`. `ci-script/build.sh builddep` should help you. We will update the documentation to mention libflint.

**Comment by gitslagga** [comment]
thanks
