### ISSUE TITLE
Replace `force_check` flag by enum with 3 variants

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#1337]
Currenlty we have flag `force_check` that validate consistency of blockchain, and check invariants of new blocks.

Propose, is to replace this flag by enum `check = None | NewBlocks | FullChain`

None - didn't check consistency, only signature of validators.
NewBlocks - check new blocks.
FullChain - check also stored blockchain.

**Comment by rtsisyk** [comment]
Fixed
