### ISSUE TITLE
Invalid block BLS multisignature on the testnet

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1474]
```
2020-01-23 12:29:47 ERROR [stegos_node] [121:0:0:441dce47d804] Invalid block received from replication: Invalid block BLS
 multisignature: epoch=121, block=5cae2690d0a8, error=Signature is not valid: hash=5cae2690d0a8
```

I have a broken database, but I can't upload it here because it is too large (1.1GB)

**Comment by rtsisyk** [comment]
This problem is caused by the inconsistent recovery procedure ("--recover" or a debug mode). Doesn't affect real production.

**Comment by vldm** [comment]
The problem is caused by incorrectly configured node, which sends blocks from mainnet to testnet clients.
Also replication wait too long for restart:
https://github.com/stegos/stegos/issues/1489
