### ISSUE TITLE
Lightnode cannot be used as upstream in replication

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#1486]
But other nodes cannot know is their connecting to light node or full.
```
2020-02-11 13:24:35 ERROR [stegos_replication::peer] [QmV1U7TTwKAXdFyZ2SKzFgdPHqu1SjMS4gjaXDPXKbBBks] Failed to send blocks: The light node can't be used a an upstream
```

**Comment by rtsisyk** [comment]
Yes, it can't be used because it doesn't have the full blockchain to serve the full node. I tried to export light/full flag to the protocol level, but I haven't found how to do that. Actually this message is just a warning and this problem doesn't block.

**Comment by rtsisyk** [comment]
This problem can't be fixed in the current libp2p-based architecture without the major rewrite.
