### ISSUE TITLE
Try to migrate to coveralls.io for code coverage

### ISSUE THREAD

**Issue by echupriyanov** [stegos/stegos#158]

**Comment by rtsisyk** [comment]
I'm fixing code coverage

**Comment by rtsisyk** [comment]
The only reliable way to get code coverage in Rust:
```
sudo apt install -y llvm clang
cargo +nightly install cargo-cov
cargo +nightly cov test --all -- --nocapture
cargo +nightly cov report --open
```

Unfortunately, due to limitation of current LVM/Rust toolchain this output cannot be properly converted to lcov output. 

Doesn't have more time to investigate.  Moving this ticket out of MVP socpe. Let's try later.

**Comment by rtsisyk** [comment]
WONTFIX
