### ISSUE TITLE
Choose Hashing Algo

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#26]

**Comment by dbmcclain** [comment]
We should standardize on SHA3 in various sizes. Most common will be SHA3-256. But there are times when variable length hashes will be used via SHAKE, which is a component of the SHA3 standard.

SHA3 is immune to length extension attacks, and so can serve as its own HMAC, unlike SHA2 which needs special padding, and often requires double hashing to gain immunity.

I suggest using an API that buries these details from the users. Just call HASH-256 when you need a standard hash computed. It should accept an indefinite number of arguments, which will be concatenated and hashed.

Lisp allowed us to hash arbitrary data objects, including those with deep structure. Rust may not be so forgiving. -- which brings up another important substrate requirement -- we need a serialization protocol for streaming objects to the network and external storage media. This should handle recursive data structures with compact representation.
