### ISSUE TITLE
Use unsigned integer for money.

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#267]
Why we should have negative balance? Having negative balance is probably a bug.

We can use https://doc.rust-lang.org/std/primitive.u64.html#method.checked_add and other checked methods if we want to controll underflow.

Additionally, we can write a wrapper around u64, to make it asserts underflow on release build too.

**Comment by rtsisyk** [comment]
Let's try to enable overflow checks first.

**Comment by rtsisyk** [comment]
https://github.com/stegos/stegos/issues/937

**Comment by dbmcclain** [comment]
This may cause failures in BulletProofs. 

Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by rtsisyk** [comment]
Unsigned values are less protected from overflows.
