### ISSUE TITLE
Choose Elliptic Curve Generators

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#27]

**Comment by dbmcclain** [comment]
All Elliptic curves come with a stated primary generator point. We need additional generators that are independent of this public generator, also to be made public, but which have no known relationship to the primary generator.

I propose using a hash of the primary generator, for some random number of iterations, and some chosen prefix, to obtain a value in the field Z_256 (for 256-bit curves like Ed25519), and then mapping that hash value back onto the curve. In this way, the resulting new point is a completely unknown multiple of the primary generator.

We publish all generators that we use. They are not secret, and neither should be their process of derivation. Everyone must have full confidence that these points were chosen in a manner than defies knowing their discrete logarithm. Only then are things like Pedersen Commitments usable.

**Comment by rtsisyk** [comment]
I think this task is already done.
