### ISSUE TITLE
Unit tests for consensus

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#273]
- [x] Implement object that will create a test Consensus enviroment:

Possible api:
- [x] Numbers of node to start
- [x] Receive msg from **external consensus Node**
- [x] Send message to **external consensus Node**
- [x] Get current state (stage, variables)
- [ ] Reset state machine

Definition of done: Test case should be implemented - 
1) Start consensus with 3 nodes; 
2) process through all stages; 
3) check that all nodes ends up in the same state.

**Comment by rtsisyk** [comment]
s/Randhound/Consensus/g

**Comment by rtsisyk** [comment]
New consensus logic can be fully tested via unit tests.

**Comment by vldm** [comment]
This task was initially about testing infrastructure, so i am closing this as obsolete.

@rtsisyk If you have additional info please provide and reopen this task.
