### ISSUE TITLE
Collect and broadcast only lowest known VRF ticket

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#308]
In https://github.com/stegos/stegos/pull/295 at collecting phase we collect all possible tickets from stakers, and our gossip broadcasts all tickets to all nodes. But we should only reach consensus about lowest ticket.
So probably it would a good idea to keeping in memory only lowest value.

**Comment by rtsisyk** [comment]
Blocked by #314

**Comment by rtsisyk** [comment]
Is it actual?

**Comment by vldm** [comment]
@rtsisyk Its one of the possible way, for now we choose to broadcast all tickets, but we can change logic later to reduce messages in network. We can reopen it when it will be more actual.

Clossing for now.
