### ISSUE TITLE
Block API Design

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#31]
Original design document by @vlebedev

**Block Header**
 - Block Number (BNO)
 - Hash of the previous block (HPREV)
 - Sum of gamma adjustments (SGA)
 - Root hash of MT_TXINS (RH_TXINS)
 - Root hash of MT_TXOUTS (RH_TXOUTS)
 - Hash of the current block (except Merkle trees): H(BNO | HPREV | SGA | RH_TXINS | RH_TXOUT) (HCURR)
 - CoSi multisignature on HCURR

**Block contents (trees)**
 - Merkle tree of transactions' inputs (MT_TXINS)
 - Merkle tree of transactions' outputs (MT_TXOUTS)

So, our blockchain is a collection of all blocks. Blocks are numbered sequentially starting from zero. Each block starting with block number 1 has a reference to a previous block via a HPREV.
It is impossible to modify anything in the block without invalidating either one of the Merkle Tree roots or HCURR.

There is only one exception from the statement in the last sentence. A node may cut the leaves from a MT_TXOUTS in previous blocks, if the newest block's MT_TXINS contains references to UTXOs in those previous blocks. By cutting them I mean replacing them with NULL marker first. So, matching TXINs and UTXOs must annihilate, i.e. be replaced with NULL markers, and a the same time the monetary balance of the whole UTXO database should stay intact. When replacing UTXO in the tree with NULL market we do not recalculate upper hashes. This is very important to understand. But we may cut the upper hash, if a sibling of the UTXO we are about to cut is already NULL. In that case we will cut the upper hash as well by replacing it with NULL.

Here is illustration of the process, by using Merkle Mountain Ranges: the picture below illustrates a range with 11 inserted leaves and total size 19, where each node is annotated with its order of insertion.

```
Height

3              14
             /    \
            /      \
           /        \
          /          \
2        6            13
       /   \        /    \
1     2     5      9     12     17
     / \   / \    / \   /  \   /  \
0   0   1 3   4  7   8 10  11 15  16 18
```

Data that gets hashed and stored in MMRs (UTXOs in our case) can eventually
be removed. As this happens, the presence of some leaf hashes in the
corresponding MMRs become unnecessary and their hash can be removed. When
enough leaves are removed, the presence of their parents may become unnecessary
as well. We can therefore prune a significant part of a MMR from the removal of
its leaves.

Pruning a MMR relies on a simple iterative process. `X` is first initialized as
the leaf we wish to prune.

1. Prune `X`.
2. If `X` has a sibling, stop here.
3. If 'X' has no sibling, assign the parent of `X` as `X`.

To visualize the result, starting from our first MMR example and removing leaves
[0, 3, 4, 8, 16] leads to the following pruned MMR:

```
Height

3             14
            /    \
           /      \
          /        \
         /          \
2       6            13
       /            /   \
1     2            9     12     17
       \          /     /  \   /  
0       1        7     10  11 15     18
```

So, eventually we will have blocks that will be comprised of block headers, but the trees themselves will contain only NULLs. We may throw aways the trees from such blocks completely, leaving only block headers, which will be a few hundred bytes each.

We may also consider to compact our database, compressing NULL objects from time to time. It is just optimization that we should decide upon later.

**Comment by rtsisyk** [comment]
I translated it to Rust:

```Rust
/// Block Header.
#[derive(Debug)]
pub struct BlockHeader {
    /// Block number, i.e. height of this block since the genesis block counting from zero.
    pub id: u64,

    /// Hash of the block previous to this in the chain.
    pub previous: Hash,

    /// Sum of gamma adjustments (SGA)
    // TODO: I'm not sure that data structure is correct
    pub excess: PubKey,

    /// Timestamp at which the block was built.
    pub timestamp: DateTime<Utc>,

    /// Merklish root of all range proofs for inputs.
    pub inputs_range_hash: Hash,

    /// Merklish root of all range proofs for output.
    pub outputs_range_hash: Hash,

    /// Hash of the current block (except Merkle trees):
    /// H(BNO | HPREV | SGA | RH_TXINS | RH_TXOUT) (HCURR)
    pub hash: Hash,

    /// CoSi multisignature on HCURR
    // TODO: which kind of data structure should be used for it?

    /// Fee originally included in the transaction this proof is for.
    pub fee: u64,
    // TODO: what is about fee?
}

/// Block.
pub struct Block {
    /// Block Header.
    pub header: BlockHeader,

    /// The list of transaction inputs.
    pub inputs: Vec<Input>,

    /// The list of transaction outputs.
    pub outputs: Vec<Output>,
}

```

**Comment by dbmcclain** [comment]
FYI... a multi-signature is simply a number representing a compressed point from our PBC G1 group, and a bitmap of which witnesses participated in the signature. 

Somewhere, (here? or known place tied to this epoch?) there needs to be an ordered list of witness public keys to which this bitmap refers.

**Comment by rtsisyk** [comment]
Let's deal with bitmap later.
