### ISSUE TITLE
Implement minimum and maximum txpool group.

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#422]
txpool should not create a new group if it size lower then 3. (lower bound)
txpool should not wait timeout, if it already contain 10 participant. (upper bound)

**Comment by dbmcclain** [comment]
I am now using an 8 bit chunking prefix on UTXOs. 101 chunks per UTXO. So I recommend allowing a maximum of 25 participants, which is 10% of hash space capacity. That should keep collisions sufficiently infrequent. You might also consider 50 participants, but then we get into long blame discovery cycles in the presence of clever attackers. So 25 participants still runs reasonably fast, and gives everyone even more anonymity.
