### ISSUE TITLE
Missing implementation of Eq for Block.

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#425]
If you try to create structure that has Block as a field, you will get an error when you will try to derive PartialEq\Eq for it.

```
 an implementation of `std::cmp::PartialEq` might be missing for `std::vec::Vec<stegos_blockchain::block::Block>`

```

**Comment by rtsisyk** [comment]
Is this problem still actual?

**Comment by vldm** [comment]
@rtsisyk yes

**Comment by rtsisyk** [comment]
I see that it has been implemented.
