### ISSUE TITLE
Validate source of randmoness for KeyBlock

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#428]
SealedKeyBlock must be signed by a leader elected by VRF. There is an open question how to validate such leader. Probably the lowest hash should be stored.

**Comment by vlebedev** [comment]
Each validator already has the lowest hash. So, each validator knows who should be the leader and who should propose the new keyblock. Sure, new keyblock must be signed by the new leader.

**Comment by rtsisyk** [comment]
Fixed by fcb2f8cdbe960bdeedc7f8c8d038a5918ce73f40
