### ISSUE TITLE
Don't recover blockchain on the start

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#441]
In order to recover faster we need to save this data in storage:
1) Last consensus group (facilitator, leader, validators). It could be saved indirectly (as last KeyBlock reference)
2) Last block timestamp, in order to recover view_change, and other timers.
3) unspent Utxo

Think about:
Mempool, txpool state, wallet state.

**Comment by rtsisyk** [comment]
Removing from the sprint in favour of https://github.com/stegos/stegos/issues/545

**Comment by rtsisyk** [comment]
Later.
