### ISSUE TITLE
Between vrf viewchanges, consensus can recieve messages from future viewchange.

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#481]
`2019-02-18 13:25:50 ERROR [stegos_consensus::state] Propose(6): a proposal from a non-leader: leader=SecurePKey(2cf473e4a000744819bd62ca71d7da78549f02221f8283a108e10453dd2ecab0b2e56068cc13015d0a9ecac4a3e91474a733e4f7b42fd4d549381a1c5407fd3a01), from=SecurePKey(14a045378badd04dede075d2361b50f97638950675d1cfab6c1ee2987752dc1b7d0cc04e17aafe109e6c1e26d0c8a38c1e7a8028a57b082f9e717246c6536bac00)`

Case:
1. epoch ended.
2. after roundtrip of VRF, consensus being not functional.
3. VRF timeout reached.
4. After timeout VRF restarts with increased view_change.
5. New consensus starts asynchronly on different nodes. So when some node receive propose it cannot define is this propose valid, or from future view_change.

**Comment by vlebedev** [comment]
Please implement the following:

1) Calculate and send the ticket along the pk_i and v (view index)
2) Wait for time period \Delta and collect tickets from other nodes
3) While waiting, keep track of tickets with index value greater then you've sent
4) Upon \Delta timer expiration, count tickets with v index equal to yours, if you see more or equal than \tau (minimal size of the group) of them, then proceed with the group formation algorithm with that tickets, discarding all others
5) If you don't have enough tickets with your v and you see tickets with any v greater than yours and you see more than \tau of the tickets with the same v, just proceed with the group formation algorithm using the tickets with that v, discarding all others
6)  If you don't have enough tickets with your v and you see tickets with any v greater than yours, and you don't see more than \tau of the tickets with the same v, then select the highest v index value out of all tickets, discard all tickets and broadcast your new ticket composed based on index value equal to highest seen v plus one, along with that new index value and start collecting tickets again (go to point 2).

**Comment by vldm** [comment]
Closed as obsolete.
