### ISSUE TITLE
Rename "secure key"  to "network key"

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#542]

**Comment by joelreymont** [comment]
I know private key and public key but what in the world are _secure key_ and _network key_?

**Comment by vldm** [comment]
@joelreymont Private\Secret and Publick keys, is a term that is related to asymmetric cryptography.

In our architecture we have multiple assymetric keypairs. One is used to sign transaction, other is used to sign network message in consensus, and other modules.

So "network key" is not a common term, but simply a description of the scope of the key.
