### ISSUE TITLE
Rework leader election

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#546]
So the solution would be like the following:

    Calculate and send the ticket along the pk_i and v (view index)
    Wait for time period \Delta and collect tickets from other nodes
    While waiting, keep track of tickets with index value greater then you've sent
    Upon \Delta timer expiration, count tickets with v index equal to yours, if you see more or equal than \tau (minimal size of the group) of them, then proceed with the group formation algorithm with that tickets, discarding all others
    If you don't have enough tickets with your v and you see tickets with any v greater than yours and you see more than \tau of the tickets with the same v, just proceed with the group formation algorithm using the tickets with that v, discarding all others
    If you don't have enough tickets with your v and you see tickets with any v greater than yours, and you don't see more than \tau of the tickets with the same v, then select the highest v index value out of all tickets, discard all tickets and broadcast your new ticket composed based on index value equal to highest seen v plus one, along with that new index value and start collecting tickets again (go to point 2).

**Comment by vldm** [comment]
This proposal is not ready:
1) It is not resilence to byzantine behaviour (p.6. take highest ticket, highest ticket could be ticket from far future) (We can avoid it by taking median of highest 2/3 tickets)
2) VRF tickets system work on the fact that broadcast block will be delivered in relative small timeout, and synchronize all nodes by this message, introducing p.6 can lead to increasaing asynchronity.
3. We should collect only highest ticket from each node, or we byzantine node can DoS by OOM some node.

**Comment by rtsisyk** [comment]
Is not actual anymore
