### ISSUE TITLE
Logging output obscures console

### ISSUE THREAD

**Issue by joelreymont** [stegos/stegos#549]
We should have a switch to flip console logging on and off. Then I could run a console with full logging in one terminal window and one with logging off in another. Otherwise, logging output interferes with typing into the console. 

This will be a moot point when we have a desktop node app and wallet but we need to do something until then. @vlebedev

**Comment by rtsisyk** [comment]
Logging is already configurable, but this feature is not documented yet. Please try to download 
[stegos-log4rs.toml.txt](https://github.com/stegos/stegos/files/2900923/stegos-log4rs.toml.txt) to the working directory of your node, rename it to "stegos-log4rs.toml" and restart the node.

**Comment by rtsisyk** [comment]
BTW, console is not started if your terminal is not TTY.  `stegos|cat` or any demonizing tool like systemd will effectively disable CLI.

**Comment by joelreymont** [comment]
> Logging is already configurable, but this feature is not documented yet. Please try to download
> [stegos-log4rs.toml.txt](https://github.com/stegos/stegos/files/2900923/stegos-log4rs.toml.txt) to the working directory of your node, rename it to "stegos-log4rs.toml" and restart the node.

Won’t do. This is a usability issue and I’m looking to make this easier for our users. I don’t want users to be downloading TOML files, I’d rather have a command-line switch or a REPL command.

Demonizing won’t work either. The easy solution I can think of is to start two terminals (TTY, yes) and disable logging in one of them. Then I can type commands into one window, undisturbed by the copious logging output in the other.

**Comment by rtsisyk** [comment]
I agree with you that node must work out of the box without mystic toml files.  But what do you propose? Log to a file by default? Add a command-line option to redirect logs to a file?

For me, logging to stdout by default is better than logging to a file. At least an user has some visibility of the process out of the box. I vote to keep logging to stdout by default and add a command line option "-log FILE" to redirect logs to a file.
