### ISSUE TITLE
Fix Bulletproof quadrant redundancy

### ISSUE THREAD

**Issue by dbmcclain** [stegos/stegos#701]
Currently our Bulletproofs can be validated by ECC point decompression that confuses the parity of decompressed point X and Y coordinates. That means that points (X, Y) as well as (-X, Y), (X, -Y), and (-X, -Y), after decompression from contained Bulletproof compressed point parameters, will pass validation.

That happens because the Bulletproof constructor passes along their challenge hash value parameters, which were based on their internal ECC point representations. Validators currently read back those hash challenges and use them in their proof validation. Then, because of the quadratic symmetry in both X, and Y of the Edwards Curve1174, the remainder of the proof will validate properly with confused signs on the coordinates.

We should fix this, so that hash parameters are recomputed on the decompressed points in the Bulletproof, so that if a point decompresses to the wrong quadrant, the hash value will be different than was used during proof construction. The Bulletproof would fail to validate if point decompression is incorrect.

It also seems more correct that the hash challenge should be generated by the validator, as would happen in an interactive challenge-response protocol. We currently bypass challenge-response by invoking the Fiat-Shamir heuristic that allows for a hash value computed against public information to serve as a random challenge value. 

Even so, there needs to be agreement on the hash challenge. And that agreement was had by accepting at face value from the proof constructor that the challenges had particular values. Instead, the validators should perform their own hash challenge construction so that we can see if we are using the same arithmetic in the remainder of the proof.

**Comment by rtsisyk** [comment]
7f9c2031916807930d59da248d86e9d53f4de507
