### ISSUE TITLE
Fix Wallet Key Decryption and Make Info Public Validatable

### ISSUE THREAD

**Issue by dbmcclain** [stegos/stegos#747]
The decrypt_key() function checks the encrypted payload against a Schnorr signature, but fails to do anything if the signature does not check.

Also, the encrypted payload can only be validated by someone who knows the necessary secret pass phrase in order to regenerate the public and secret encryption keys. By making the transient public key available to everyone, we can write utility programs later to scan databases for corrupt encrypted keys

**Comment by rtsisyk** [comment]
Merged
