### ISSUE TITLE
Consensus test plan

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#752]
Draft of testcases:

Smoke tests:
1) N epoch without minority of nodes.

Macro-block consensus:
== easy ==
1) Consensus regular (Round of consensus)
2) Consensus view_change in case of dead leader. (check if on dead leader consensus will try to produce block)
== medium ==
3) Consensus with byzantite (below, majority, and above majority)
3.1) Invalid proposes/prevotes/precommits
3.2) Check locking, byzantine sends outdated propose/precommit/prevote
== hard ==
3.3) Multiple proposes for same round
3.4) Multiple prevotes/precommits for same round 
4) timeouts incrementation

Micro-block consensus:
== easy ==
1) View change in case of dead leader.
2) leader in partition receive conflict block, resolving fork.
== medium ==
3) timeouts incrementation.
4) slashing in case of duplicate blocks.

Conflicting code:
1) Conflicted monetary block (valid/invalid)
2) Conflicted key block (valid/invalid)

**Comment by vldm** [comment]
Mostly done.

Not done parts, are :

slashing,

And

Consensus with byzantite (below, majority, and above majority)
3.1) Invalid proposes/prevotes/precommits
3.2) Check locking, byzantine sends outdated propose/precommit/prevote
== hard ==
3.3) Multiple proposes for same round
3.4) Multiple prevotes/precommits for same round

**Comment by rtsisyk** [comment]
1 validator was restarted with database clearing.
 Rest of nodes run into different view_change forks (some of view_change messages was not delivered to some of nodes)

**Comment by vldm** [comment]
We probably finish with consensus testing.
@rtsisyk I moved your test case into persistence test plan.
