### ISSUE TITLE
Network cannot synchronize.

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#760]
At devnet we have following case:
1) 1 validator was restarted with database clearing.
2) Rest of nodes run into different view_change forks (some of view_change messages was not delivered to some of nodes)

in result our network is being not synchronized and stucked.

this bug is related to next functional:
#758 
#314

**Comment by vldm** [comment]
Fixed in #767  ?

**Comment by rtsisyk** [comment]
I suppose that it has been fixed. Let's add this problem to our test plan.
