### ISSUE TITLE
Unicast messages are duplicated

### ISSUE THREAD

**Issue by venticello** [stegos/stegos#769]
![uncast](https://user-images.githubusercontent.com/1232990/56454891-5bd1d800-6360-11e9-9b92-03cff4c0ac04.png)
Version: Stegos 0.4.38 (2bc85cb 2019-04-19)

I launched 2 docker images with different keys and databases. I sent a message to the first public network key, the message was displayed 5 times.
If I send a message to myself, it is displayed only 1 time.

**Comment by echupriyanov** [comment]
@venticello great thanks for reporting!

could you, please, provide some more details on your config? Did you specify node configuration file (stegos.toml)? How did you run your docker containers?

**Comment by venticello** [comment]
1st:
docker run -it --name devtest -v "$(pwd):/stegos"  -w /stegos --rm rust:1.34.0-slim-stretch ./stegos -c stegos.toml

``` 
//stegos.toml
[general]
chain = "devnet"
```

2nd:
 docker run -it --name devtest2 -v "$(pwd):/stegos" -w /stegos --rm rust:1.34.0-slim-stretch ./stegos -c stegos2.toml

```
//stegos2.toml
[general]
chain = "devnet"

[keychain]
private_key = "node2/stegos.skey"
public_key = "node2/stegos.pkey"
```

**Comment by echupriyanov** [comment]
@venticello thanks a lot! looking into it.
