### ISSUE TITLE
Fix the Pt::Ord trait to avoid bitwise comparison

### ISSUE THREAD

**Issue by dbmcclain** [stegos/stegos#824]
Compressed ECC points, type Pt([u8;32]), are not unique representations of underlying points. Hence bitwise comparison of the compressed format may not catch alternate encodings. Our codebase always produces a canonical encoding, and as long as we are comparing against points created by our codebase, the use of bitwise comparison is valid.

But external agents - either malicious or incompetent - could produce alternate compressed point encodings that look different from canonical encoding, yet actually represents the same underlying ECC point.

The correct way to compare two compressed points is to first decompress them, then perform coordinate-wise comparison. Or else re-compress back to canonical form before bitwise comparison.

There is no simple way to detect a non-canonical representation without attempting a decompression.

**Comment by rtsisyk** [comment]
Merged.
