### ISSUE TITLE
Remove Y parity bit from compressed point representation

### ISSUE THREAD

**Issue by dbmcclain** [stegos/stegos#831]
As per D.J.Bernstein, for Edwards curves is is sufficient to use only the X coordinate for a compressed point representation.

https://twist.com/a/39362/ch/95451/t/830513/

**Comment by dbmcclain** [comment]
This issue has been thoroughly reworked into serious cleanup of base Curve1174 crypto code. We *do not* remove the Y parity bit from compressed point representations, because theory does not match reality. We actually need it to guide the outcomes from Fq Sqrt() operations.

**Comment by rtsisyk** [comment]
Why we should do that?

**Comment by dbmcclain** [comment]
You must not do this. Already tried and produces failures. While curve equations admit possible both signs for Y, the wrong parity is not in the same principal group. 

Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by dbmcclain** [comment]
Failures will be sporadic but show up in failed Schmitt signature and BulletProof validations from known good signatures. 

Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by dbmcclain** [comment]
Damn autocorrect SCHNORR SIGNATURES

Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by dbmcclain** [comment]
Also sometimes failed decryptions. Any place that uses curve points. Public keys


Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by dbmcclain** [comment]
While I initially tried to use symmetry of equation to elide Y parity requirement I see that this fails. And furthermore my prescaling by cofactor, h, accomplishes nothing useful. 

We are currently broken and need to reinstate check on decompression to assure we are in principal subgroup. 

Need to remove prescaling on compression, preserve Y parity in compressed representation, and perform subgroup membership test on decompression. 

Subgroup membership test checks that prime multiple, F_r, of point is group identity element (X,Y) = (0, 1) in affine coordinates 

Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by dbmcclain** [comment]
There are 4 distinguished points on an Edwards curve. Point (X, Y) = (0,1) is the group additive identity element. 

Pont (0, -1) is on curve but not in principal subgroup, and has order 2. Points (1, 0) and (-1, 0) are also on curve but not in principal subgroup and have additive order 4. 

If point (X, Y) is on curve and also in principal subgroup, then it’s additive inverse (-X, Y) is also on curve and in principal subgroup. 

One can show that 
(X, -Y) is on curve but = (0, -1) - (X, Y)
And similarly for (Y, X) and (Y, -X) and their negatives. 

Hence these other symmetric points cannot also be in prime order principal subgroup and must be rejected as invalid points. 

Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by dbmcclain** [comment]
Perhaps I worded too strongly. Cofactor prescaling on compression / decompression does accomplish prevention of invalid points. 

It makes possible public key synonyms for points in principal subgroup. But without correct Y parity these would likely fail BulletProofs and signatures. 

So maybe we are not broken. Current system places computation burden on point compression and speeds up point decompression.

We should probably leave as currently implemented. 

Dr. David McClain
Refined Audiometrics Laboratory, LLC
