### ISSUE TITLE
Add r-value info from, and spender hash to encrypted payloads

### ISSUE THREAD

**Issue by dbmcclain** [stegos/stegos#914]
In support of proof of spending, we need to allow wallets to record the secret r-value used for keying of the encrypted payload, and we need to bury proof of spender ID in the encrypted payload.

So encrypt_payload will need to remember and return the keying seed, r, to the caller. And inside the encrypted payload we will add H(P_spender) alongside amount, gamma, delta.

**Comment by rtsisyk** [comment]
Needed for Payment Certificates.

**Comment by rtsisyk** [comment]
Done
