### ISSUE TITLE
Re-enable Rust overflow checks

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#937]
Crypto library has been updated to use overflows properly. Let's try to enable `overflow-checks` both for debug and release builds and see how it affects the performance.

**Comment by dbmcclain** [comment]
This may fail sporadically. Crypto lib was explicitly written to allow for word wrapping overflows. Indeed may require them. 

Dr. David McClain
Refined Audiometrics Laboratory, LLC

**Comment by rtsisyk** [comment]
I see 10% slow down on bulletproof validation and 15% slowdown on complex blockchain bench. Let's forget this idea.
